# Start from a base ubuntu (linux) install
FROM ubuntu:20.04

# Set the working directory in the container
WORKDIR /home/cprojects

# Install gcc and stuff
RUN apt-get update && \
  apt-get install -y gcc make
