version: '3.8'

services:
  app1:
    image: bitnami/laravel:11-debian-12
    container_name: laravel_consume_api1
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./app1:/app
    command: tail -f /dev/null
    depends_on:
      - db1
    environment:
      - DB_HOST=db1
      - DB_PORT=3306
      - DB_DATABASE=consumeApi
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - consumeapinetwork1

  db1:
    image: mariadb:10.6.19-focal
    container_name: laravel_consume_api_db
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=consumeApi
      - MARIADB_USER=laravel
      - MARIADB_PASSWORD=laravelPwd
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - ./db_data1:/var/lib/mysql:Z
    networks:
      - consumeapinetwork1

  adminer1:
    image: adminer:4.8.1-standalone
    restart: unless-stopped
    ports:
      - 9095:8080
    networks:
      - consumeapinetwork1

  server2:
    container_name: flask_api
    restart: unless-stopped
    image: python:3.10
    working_dir: /app
    command: tail -f /dev/null
    ports:
      - 5000:5000
    volumes:
      - ./app2:/app
    depends_on:
      - db2
    environment:
      - DB_HOST=db2
      - DB_PORT=3306
      - DB_DATABASE=restapi2
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - consumeapinetwork1

  db2:
    image: mariadb:10.6.19-focal
    container_name: flask_api_db
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=restapi2
      - MARIADB_USER=flask
      - MARIADB_PASSWORD=flaskPwd
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - ./db_data2:/var/lib/mysql:Z
    networks:
      - consumeapinetwork1

  adminer2:
    image: adminer:4.8.1-standalone
    restart: unless-stopped
    ports:
      - 9096:8080
    networks:
      - consumeapinetwork1

networks:
  consumeapinetwork1:
    driver: bridge
