version: '3.8'

services:
  server:
    container_name: flask_server
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5008:5000
    volumes:
      - ./app:/app
    networks:
      - mynetwork
    depends_on:
      - db

  db:
    image: mariadb:10.6.19-focal
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./mydata:/var/lib/mysql:Z
    networks:
      - mynetwork

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 9092:8080
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
