version: '3.8'

services:
  app:
    image: bitnami/laravel:11-debian-12
    container_name: laravel_consume_api
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh entrypoint.sh # docker exec -it laravel_api /bin/bash
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=consumeApi
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - consumeapinetwork

  db:
    image: mariadb:10.6.19-focal
    container_name: laravel_consume_api_db
    restart: unless-stopped
    environment:
      - MARIADB_DATABASE=consumeApi
      - MARIADB_USER=laravel
      - MARIADB_PASSWORD=laravelPwd
      - MARIADB_ROOT_PASSWORD=root
    volumes:
      - ./db_data:/var/lib/mysql:Z
    networks:
      - consumeapinetwork

  adminer:
    image: adminer:4.8.1-standalone
    restart: unless-stopped
    ports:
      - 9090:8080
    networks:
      - consumeapinetwork

networks:
  consumeapinetwork:
    driver: bridge
