version: '3.8'

services:
  nginx_example:
    image: nginx:latest
    container_name: nginx_example
    ports:
      - "9091:80"
    volumes:
      - ./myfiles/:/usr/share/nginx/html
    restart: unless-stopped
    # TODO:
