version: '3.8'

services:
  nginx_example2:
    image: nginx:latest
    container_name: nginx_example2
    ports:
      - "9093:80"
    volumes:
      - ./myfiles/:/usr/share/nginx/html
    restart: unless-stopped
