services:
  db:
    image: mariadb:10.6.19-focal
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./mydata:/var/lib/mysql:Z

  adminer:
    image: adminer:4.8.1-standalone
    restart: always
    ports:
      - 9092:8080
