version: '3.8'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
    volumes:
      - ./mydata:/var/lib/mysql:Z

  adminer:
    image: adminer
    restart: always
    ports:
      - 9092:8080
